### ISSUE TITLE
M1S DOCK目前只能在linux下开发嘛

### ISSUE THREAD

**Issue by linshire** [sipeed/M1s_BL808_example#1]
我找了一下，似乎并没有找到有关cdk的工程和指导（可能是我没有找到），可以提供一些指导嘛

**Comment by taonyx** [comment]
我们没有尝试过CDK，不过在windows下可以使用VSCode或CLion开发C/C++代码，使用wsl2的linux环境。可以搜索一下相关的配置教程。

**Comment by sakumisu** [comment]
不支持 CDK ，只能使用命令行，windows 和 linux都用命令行

**Comment by linshire** [comment]
好的谢谢了
