### ISSUE TITLE
Model Deployement

### ISSUE THREAD

**Issue by devendraaa** [sipeed/M1s_BL808_example#16]
I have Trained a Custom model from MaixHub.

Now I have 2 files Model.blai & Report.json.
Could you guide me on How to Deployed This model On Sipeed M1s?

And how can I upload a Python script to do some tasks Related to this model?

Already I have Flash Firmware using Bouffalo Lab Tool.

Thank You.

**Comment by taonyx** [comment]
How about take a look at c906_app/tom_and_jerry_classification_demo.

The main.c has contained all operations about blai/sblai model generated by MaixHub.

If there is still any problem, issue again to let me know.

**Comment by devendraaa** [comment]
Thank you for your response,
But I want to use python code to run the Custom model instead of main.c

Could you guide me how can I use pyrhon code to run the Maixhub Custom Model
